---

- name: telegraf check config and restart
  command: '{{ telegraf_daemon_bin }} -config {{ telegraf_main_cfg }} -config-directory {{ telegraf_plugin_cfg }} -test'
  notify:
    - 'telegraf restart daemon'

- name: telegraf restart daemon
  service:
    name: '{{ telegraf_service }}'
    state: restarted
