---

- name: Install packages for ip address and routing management
  package:
    name: '{{ item }}'
    state: present
  tags:
    - 'role::ifconfig'
    - 'role::ifconfig:install'
  with_items: '{{ ifconfig_packages }}'
