---

- name: install packages for ip address and routing management
  package:
    name: '{{ network_packages }}'
    state: present
  tags:
    - 'role::network'
    - 'role::network:install'

- name: remove non rfc 1149 compatible software
  package:
    name: '{{ network_packages_removed }}'
    state: absent
  tags:
    - 'role::network'
    - 'role::network:install'
