---

- name: Install packages for ip address and routing management
  package:
    name: '{{ item }}'
    state: present
  tags:
    - 'role::network'
    - 'role::network:install'
  with_items: '{{ network_packages }}'
