---

- name: install grub related packages
  package:
    name: '{{ grub_packages }}'
    state: present

- name: remove unused grub packages
  package:
    name: '{{ grub_packages_removed }}'
    state: absent
