---

- name: configure mariadb server
  template:
    src: etc/my.cnf.j2
    dest: '{{ mariadb_conf }}'
    owner: root
    group: root
    mode: 0644
    seuser: system_u
    serole: object_r
    setype: mysqld_etc_t
    selevel: s0
  notify:
    - 'check mariadb and restart'
