---

- name: install mariadb related packages
  package:
    name: '{{ mariadb_packages }}'
    state: present
  notify:
    - 'mariadb restart daemon'
    - 'mariadb remove anonymous users'
    - 'mariadb remove test database'
