---

- name: install mariadb related packages
  package:
    name: '{{ item }}'
    state: present
  tags:
    - 'role::mariadb'
    - 'role::mariadb:install'
  with_items: '{{ mariadb_packages }}'
  notify:
    - 'restart mariadb'

- name: enable mariadb service
  service:
    name: '{{ mariadb_service }}'
    state: started
    enabled: yes
  tags:
    - 'role::mariadb'
    - 'role::mariadb:install'
