---

- name: install mariadb related packages
  package:
    name: '{{ item }}'
    state: present
  with_items: '{{ mariadb_packages }}'
  notify:
    - 'mariadb restart daemon'
    - 'mariadb remove anonymous users'
    - 'mariadb remove test database'
