---
# -*- coding: utf-8 -*-

before_script:
  - pip install --upgrade ansible ansible-lint yamllint
  - ansible --version
  - ansible-lint --version
  - yamllint --version

stages:
  - lint

ansible-lint:
  stage: lint
  script:
    - for dir in *; do test -d "$dir" && echo "$dir" && ansible-lint "$dir"; done

yamllint:
  stage: lint
  script:
    - for dir in *; do test -d "$dir" && echo "$dir" && yamllint -c ./.testenv/yamllint.yml "$dir"; done

bcp_check:
  stage: lint
  script:
    - for file in */tasks/*; do egrep -H '^- name:.*[[:upper:]]' "$file" && exit 1; done; exit 0

# vim: set ts=2 sw=2 tw=2 :
