---
# -*- coding: utf-8 -*-

before_script:
  - pip install --upgrade ansible ansible-lint

stages:
  - lint

run-lint:
  stage: lint
  script:
    - ansible --version
    - ansible-lint --version
    - for dir in *; do test -d "$dir" && ansible-lint "$dir"; done

# vim: set ts=2 sw=2 tw=2 :
