---

- name: Install nginx-related packages
  apt:
    name: '{{ item }}'
    state: 'latest'
    install_recommends: false
  when: item is defined and item
  with_items:
    - 'nginx'
    - '{{ nginx_packages_extra | d() }}'

- name: Create custom directory
  file:
    path: '/etc/nginx/{{ item }}'
    state: 'directory'
    owner: 'root'
    group: 'root'
    mode: '0755'
  with_items: [ 'vhosts.d' ]
