---

- name: install nginx-related packages
  package:
    name: '{{ item }}'
    state: present
  when: item is defined and item
  with_items: '{{ nginx_packages }}'

- name: create directory for vhosts
  file:
    path: '{{ nginx_vhosts_dir }}'
    state: directory
    owner: root
    group: root
    mode: 0755
