---

- name: Install nginx-related packages
  apt:
    name: '{{ item }}'
    state: 'latest'
    install_recommends: false
  when: item is defined and item
  with_items:
    - 'nginx'
    - '{{ nginx_packages_extra | d() }}'

- name: Divert nginx.conf
  command: dpkg-divert --quiet --local --divert /etc/nginx/nginx.conf.dpkg-divert
           --rename /etc/nginx/nginx.conf creates=/etc/nginx/nginx.conf.dpkg-divert

- name: Create nginx main configuration
  template:
    src: 'etc/nginx/nginx.conf.j2'
    dest: '/etc/nginx/nginx.conf'
    owner: 'root'
    group: 'root'
    mode: '0644'
  notify: [ 'Check nginx and reload' ]
