---

- name: check mariadb and restart
  shell: '{{ mariadb_server_bin }} --help --verbose --skip-networking 1>/dev/null'
  notify:
    - 'restart mariadb'

- name: restart mariadb
  service:
    name: '{{ mariadb_service }}'
    state: restarted
