---

- name: configure ssh
  template:
    src: etc/ssh/sshd_config.j2
    dest: '{{ ssh_daemon_cfg }}'
    owner: root
    group: root
    mode: 0644
    seuser: system_u
    serole: object_r
    setype: etc_t
    selevel: s0
  notify: ['restart sshd']
