---

- name: include os specific vars
  include_vars: '{{ item }}'
  with_first_found:
    - '{{ ansible_distribution }}_{{ ansible_distribution_major_version }}.yml'
    - '{{ ansible_os_family }}.yml'
  tags:
    - 'role::rsyslog'
    - 'role::rsyslog:install'
    - 'role::rsyslog:config'

- include: installation.yml
- include: configuration.yml
