---

- name: remove conflicting packages
  apt:
    name: '{{ postfix_packages_removed }}'
    state: absent
    purge: yes
  tags:
    - 'role::postfix'
    - 'role::postfix:install'
  when: ansible_os_family == 'Debian'

- name: remove conflicting packages
  package:
    name: '{{ postfix_packages_removed }}'
    state: absent
  tags:
    - 'role::postfix'
    - 'role::postfix:install'
  when: ansible_os_family != 'Debian'

- name: install postfix related packages
  package:
    name: '{{ postfix_packages }}'
    state: present
  tags:
    - 'role::postfix'
    - 'role::postfix:install'
