---

- name: configure ntp
  template:
    src: etc/ntp.conf.j2
    dest: '{{ ntp_cfg }}'
    owner: root
    group: root
    mode: 0644
    seuser: system_u
    serole: object_r
    setype: net_conf_t
    selevel: s0
  notify:
    - 'ntp restart daemon'

- name: enable and start ntp service
  service:
    name: '{{ ntp_service }}'
    state: started
    enabled: yes
