---

- name: install ntp related packages
  package:
    name: '{{ ntp_packages }}'
    state: present

- name: remove ntp conflicting packages
  package:
    name: '{{ ntp_packages_removed }}'
    state: absent
  when: ntp_packages_removed is defined
