---

- name: install ntp related packages
  package:
    name: '{{ item }}'
    state: present
  with_items: '{{ ntp_packages }}'

- name: remove ntp conflicting packages
  package:
    name: '{{ item }}'
    state: absent
  with_items: '{{ ntp_packages_remove }}'
  when: ntp_packages_remove is defined
