---

- name: install ntp related packages
  package:
    name: '{{ item }}'
    state: present
  with_items: '{{ ntp_packages }}'

- name: remove ntp conflicting packages
  package:
    name: '{{ ntp_packages_removed }}'
    state: absent
  when: ntp_packages_removed is defined
