---

- name: Divert default configuration file
  command: 'dpkg-divert --quiet --local --divert {{ snmp_daemon_cfg }}.dpkg-divert --rename {{ snmp_daemon_cfg }}'
  args:
    creates: '{{ snmp_daemon_cfg }}.dpkg-divert'
  tags:
    - 'role::snmp'
    - 'role::snmp:config'
  notify: [ 'Restart snmpd' ]
  when: 'ansible_os_family == "Debian"'

- name: Configure snmpd daemon variables
  template:
    src: 'etc/default/snmpd.{{ ansible_os_family }}.j2'
    dest: '{{ snmp_daemon_env_cfg }}'
    owner: root
    group: root
    mode: 0644
    seuser: system_u
    serole: object_r
    setype: etc_t
    selevel: s0
  tags:
    - 'role::snmp'
    - 'role::snmp:config'
  notify: [ 'Restart snmpd' ]

- name: Configure snmpd service
  template:
    src: etc/snmp/snmpd.conf.j2
    dest: '{{ snmp_daemon_cfg }}'
    owner: root
    group: root
    mode: 0600
    seuser: system_u
    serole: object_r
    setype: etc_t
    selevel: s0
  tags:
    - 'role::snmp'
    - 'role::snmp:config'
  notify: [ 'Restart snmpd' ]

- name: Configure snmp client connection to localhost
  template:
    src: etc/snmp/snmp.local.conf.j2
    dest: '{{ snmp_local_cfg }}'
    owner: root
    group: root
    mode: 0600
    seuser: system_u
    serole: object_r
    setype: etc_t
    selevel: s0
  tags:
    - 'role::snmp'
    - 'role::snmp:config'
  notify: [ 'Restart snmpd' ]

- name: Create snmpd extension script directory
  file:
    path: '{{ snmp_extension_scripts }}'
    state: directory
    owner: root
    group: root
    mode: 0755
    seuser: system_u
    serole: object_r
    setype: lib_t
    selevel: s0
  tags:
    - 'role::snmp'
    - 'role::snmp:config'

- name: Install snmpd extension scripts
  copy:
    src: usr/local/lib/snmpd/
    dest: '{{ snmp_extension_scripts + "/" }}'
    owner: root
    group: root
    mode: 0755
    seuser: system_u
    serole: object_r
    setype: lib_t
    selevel: s0
  tags:
    - 'role::snmp'
    - 'role::snmp:config'
