---

- name: Install snmp related packages
  package:
    name: '{{ item }}'
    state: present
  with_items: '{{ snmp_packages }}'

- name: Install additional snmp related packages
  package:
    name: '{{ item }}'
    state: present
  with_items: '{{ snmp_additional_packages }}'
