---

- name: install snmp related packages
  package:
    name: '{{ item }}'
    state: present
  tags:
    - 'role::snmp'
    - 'role::snmp:install'
  with_items: '{{ snmp_packages }}'

- name: install additional snmp related packages
  package:
    name: '{{ item }}'
    state: present
  tags:
    - 'role::snmp'
    - 'role::snmp:install'
  with_items: '{{ snmp_additional_packages }}'
