---

- name: install snmp related packages
  package:
    name: '{{ snmp_packages }}'
    state: present
  tags:
    - 'role::snmp'
    - 'role::snmp:install'

- name: install additional snmp related packages
  package:
    name: '{{ snmp_additional_packages }}'
    state: present
  tags:
    - 'role::snmp'
    - 'role::snmp:install'
