---

- name: Install snmp related packages
  package:
    name: '{{ item }}'
    state: present
  with_items: '{{ snmpd_packages }}'

- name: Install additional snmp related packages
  package:
    name: '{{ item }}'
    state: present
  with_items: '{{ snmpd_additional_packages }}'
