---

- name: Install snmp related packages
  apt:
    name: '{{ item }}'
    state: 'latest'
    install_recommends: false
  with_flattened:
    - [ 'snmp', 'snmpd' ]
    - snmpd_packages

- name: Divert default configuration file
  command: dpkg-divert --quiet --local --divert /etc/snmp/snmpd.conf.dpkg-divert --rename /etc/snmp/snmpd.conf
  args:
    creates: '/etc/snmp/snmpd.conf.dpkg-divert'
  notify: [ 'Restart snmpd' ]

- name: Configure snmpd daemon variables
  template:
    src: 'etc/default/snmpd.j2'
    dest: '/etc/default/snmpd'
    owner: 'root'
    group: 'root'
    mode: '0644'
  notify: [ 'Restart snmpd' ]

- name: Configure local SNMP credentials
  template:
    src: 'etc/snmp/snmp.local.conf.j2'
    dest: '/etc/snmp/snmp.local.conf'
    owner: 'root'
    group: 'root'
    mode: '0600'
